version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    command: ['npm', 'run', 'start']

  nginx:
      build:
        dockerfile: Dockerfile
        context: ./nginx
      container_name: study-meet-nginx
      ports:
        - "80:80"
      links:
        - backend