version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    ports:
      - '3000:3000'
    volumes:
      - /app/backend/node_modules
      - ./:/app/backend
    command: ['npm', 'run', 'start']

  test:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/backend/node_modules
      - ./:/app/backend
    command: ['npm', 'run', 'test']
