name: Deploy StudyMeet
on:
  push:
    branches:
      - master
      - docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - run: docker build -t cjstkrak/studymeet-test-app -f ./Dockerfile.dev ./
      - run: docker run -e CI=true cjstkrak/studymeet-test-app npm run test

      - run: docker build -t cjstkrak/studymeet-backend-app ./
      - run: docker build -t cjstkrak/studymeet-nginx ./nginx

      - run: docker push cjstkrak/studymeet-backend-app
      - run: docker push cjstkrak/studymeet-nginx

      - name: Generate deploym!ent package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB!!
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-fullstack-app-v3
          environment_name: Docker-fullstack-app-v3-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-2-654654225421
          region: ap-northeast-2
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
